import overlay from '../data/admin-content.json';
import scheduleSeed from '../data/schedule-events.json';
import resultsSeed from '../data/results.json';
import winsSeed from '../data/wins.json';
import standingsSeed from '../data/standings.json';
import milestonesSeed from '../data/milestones.json';
import rosterSeed from '../data/roster-profiles.json';
import profilesSeed from '../data/driver-profiles.json';
import driversSeed from '../data/drivers.json';
import chartersSeed from '../data/charters.json';
import iracingSeed from '../data/iracing-garage.json';
import newsSeed from '../data/news.json';
const choose = (name, seed) => overlay.datasets?.[name] ?? seed;
export const scheduleEvents = choose('schedule-events', scheduleSeed);
export const results = choose('results', resultsSeed);
export const wins = choose('wins', winsSeed);
export const standings = choose('standings', standingsSeed);
export const milestones = choose('milestones', milestonesSeed);
export const rosterProfiles = choose('roster-profiles', rosterSeed);
export const driverProfiles = choose('driver-profiles', profilesSeed);
export const drivers = choose('drivers', driversSeed);
export const charters = choose('charters', chartersSeed);
export const iracingGarage = choose('iracing-garage', iracingSeed);
export const news = choose('news', newsSeed);
